<?php
/**
 * @author Harry Tang <harry@modernkernel.com>
 * @link https://modernkernel.com
 * @copyright Copyright (c) 2016 Modern Kernel
 */


namespace modernkernel\dotdotdot;

use yii\base\Widget;
use yii\helpers\Html;

/**
 * Class Dotdotdot
 * @package modernkernel\dotdotdot
 */
class Dotdotdot extends Widget
{

    public $tag = 'span';
    public $content = '';
    public $options = [];
    public $clientOptions = [];

    /**
     * @inheritdoc
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (empty($this->options['id'])) {
            $this->options['id'] = $this->getId();
        }
    }

    /**
     * @inheritdoc
     */
    public function run()
    {
        echo Html::beginTag($this->tag, $this->options);
        echo $this->content;
        echo Html::endTag($this->tag);

        $this->registerPlugin();
        $this->registerJS();
    }

    /**
     * Registers plugin and the related events
     */
    protected function registerPlugin()
    {
        $view = $this->getView();
        Asset::register($view);
    }

    /**
     * Register JS
     */
    protected function registerJS()
    {
        $clientOptions = !empty($this->clientOptions) ? json_encode($this->clientOptions) : '{}';
        $script = '$("#' . $this->getId() . '").dotdotdot(' . $clientOptions . ');';
        $this->view->registerJs($script);
    }

} 